config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'templates#index'
  resources :templates
  # resources :template_questions

  get '/templates/validate_name/:name', to: 'templates#validate_name'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/template.rb
class Template < ApplicationRecord
  has_many :template_questions, dependent: :destroy
  accepts_nested_attributes_for :template_questions, allow_destroy: true, reject_if: :all_blank
  # validates :template_questions, length: {minimum:1, maximum: 10, message: ": Deve ter no mínimo 1 e no máximo 10 questões"}
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validate :maximum_and_minimum_questions


  def maximum_and_minimum_questions
    total_questions = self.template_questions.reject(&:marked_for_destruction?).size
    if total_questions > 10
      self.errors.add(:base, "Deve ter no máximo 10 questões!")
    elsif total_questions < 1
      self.errors.add(:base, "Template deve ter no mínimo 1 questão!")
    end
  end
end

app/models/template_question.rb
class TemplateQuestion < ApplicationRecord
  belongs_to :template, touch: true
  enum question_type: { text: 1, number: 2, date: 3 }

  validates :question_type, :question_title, presence: true

  def self.question_type_to_select
    TemplateQuestion.question_types.map { |type| [type[0].to_s.humanize, type[0].to_s] }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_action :set_template, only: [:edit, :update, :show, :destroy]

  def index
    @templates = Template.all
  end

  def show
    @questions = @template.template_questions
  end

  def new
    @template = Template.new
  end

  def create
    @template = Template.new(params_template)
    if @template.save
      redirect_to templates_path, notice: "Template cadastrado com sucesso!"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @template.update(params_template)
      redirect_to templates_path
    else
      render :edit
    end
  end

  def destroy
    if @template.destroy
      redirect_to templates_path, notice: "Template excluído com sucesso!"
    else
      render :index
    end
  end

  def validate_name
    name = params[:name]
    resposta = Template.find_by(name: name).blank?
    render json: { resposta: resposta }
  end


  private

  def params_template
    params.require(:template).permit(:name,
      template_questions_attributes: [:id, :question_title, :question_type, :_destroy])
  end

  def set_template
    @template = Template.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Questions</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" type="text/css" href="style.css" />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Poppins:wght@400;500&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>
      <p>Templates</p>
    </header>
    <section>
      <%= yield %>
    </section>
    <aside>
      <span> <%= link_to 'HOME', root_path %></span>
    </aside>
  </body>
</html>

app/views/templates/_form.html.erb
<% if @template.errors.any?%>
  <div class="alert alert-danger alert-warning alert-dismissible fade show" role="alert">
      <ul>
        <% @template.errors.full_messages.each do |message| %>
          <li> <%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>

<%= simple_form_for @template do |f| %>
  <div>
    <div class="field_control">
      <span>Nome do Template</span>
      <%= f.input :name,
        as: :text,
        presence: true,
        label: false,
        input_html: {
          id: "template_name",
          cols: 60
        }
      %>
    </div>
    <div>
      <span class="button button-new "><%= link_to_add_association 'ADICIONAR QUESTÃO', f, :template_questions, 'data-association-insertion-node' => "#template_questions" %></span>
    </div>
    <div id="template_questions">
      <%= f.simple_fields_for :template_questions do |question| %>
        <%= render 'template_question_fields', f: question %>
      <% end %>
    </div>
    <p>
      <button type="submit" id="template_submit">
        ENVIAR
      </button>
    </p>
  </div>
<% end %>

<script type="text/javascript">
  $( "#template_name" ).change(function() {
    $.ajax({
      url: '/templates/validate_name/' + $(this).val(),
      type: 'get',
      dataType: 'JSON',
      success: function (json) {
        if(json.resposta){
          $('#template_submit').prop("disabled", false);
        } else {
          alert("NOME DE TEMPLATE JA UTILIZADO!");
          $('#template_submit').prop("disabled", true);
        }
      }
    });
  });
</script>

app/views/templates/_template_question_fields.html.erb
<div class="nested-fields">
  <div class="panel-cocoon">
      <div class="field_control">
        <span>Título da Questão</span>
        <%= f.input :question_title,
        as: :text,
        label: false,
        input_html: {
          rows: 3,
          cols: 60
        }
      %>
      </div>
      <div class="field_control">
        <span>Tipo da Questão</span>
        <%= f.input :question_type,
        required: true,
        collection: TemplateQuestion.question_type_to_select,
        prompt: "Select type",
        label: false %>
      </div>
      <div class="delete">
        <span class="button button-delete"><%= link_to_remove_association "EXCLUIR", f %></span>
      </div>
  </div>
</div>

app/views/templates/edit.html.erb
<div class="container">
  <div class="container-header">
    <span>Editando Template</span>
  </div>
  <%= render 'form' %>
</div>

app/views/templates/index.html.erb
<div class="container">
  <div class="barra-title container-header">
    <span>Lista de Templates</span>
    <div class="button button-new"><%= link_to "CADASTRAR TEMPLATE", new_template_path %></div>
  </div>
  <div>
    <table>
      <thead>
        <tr>
          <th>NOME</th>
          <th>DATA DE ATUALIZAÇÃO</th>
          <th class="acao">AÇÕES</th>
        </tr>
      </thead>
      <tbody>
        <% if @templates.blank? %>
          <tr>
            <td colspan="3" style="text-align: center">Nenhum template cadastrado</td>
          </tr>
        <% else %>
          <% @templates.each do |template| %>
          <tr>
            <td>
              <span class="button-show"><%= link_to template.name, template_path(template) %></span>
            </td>
            <td>
              <%= template.updated_at %>
            </td>
            <td class="acao">
              <span class="button button-edit "><%= link_to "EDITAR", edit_template_path(template)  %></span>
              <span class="button button-delete"><%= link_to "EXCLUIR", template_path(template), method: :delete, data:{ confirm: "Tem certeza?" } %></span>
            </td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/templates/new.html.erb
<div class="container">
  <div class="container-header">
    <span>Novo Template</span>
  </div>
  <%= render 'form' %>
</div>

app/views/templates/show.html.erb
<div class="container">
  <div class="container-header">
    <span></span>
    <p>Template: <%= @template.name.upcase %></p>
  </div>
<hr>
  <h3>Questões cadastradas</h3>
  <% @questions.each do |question| %>
    <div class="question">
      <div>
        <strong>Título da Questão:</strong>
        <span><%= question.question_title %></span>
      </div>
      <div>
        <strong>Tipo: </strong>
        <span><%= question.question_type&.upcase %></span>
      </div>
      <div>
        <strong>Updated_at: </strong>
        <span><%= question.updated_at %></span>
      </div>
    </div>
  <% end %>
</div>